vich_uploader:
        db_driver: orm
        mappings:
                post_files:
                    uri_prefix: '/uploads/images'
                    upload_destination: '%kernel.project_dir%/public/uploads/images'
                    namer: vich_uploader.namer_uniqid